### ISSUE TITLE
Android Build Problem 

### ISSUE THREAD

**Issue by somenath1435** [scorelab/AnimalRescue#21]
The following issue is happening :

![Screenshot (16)](https://user-images.githubusercontent.com/43093724/73582673-2e4fb880-44b4-11ea-9fdd-7a73bba0a883.png)

Command used: react-native run-android
Note: App is installing fine using android studio

**Comment by somenath1435** [comment]
@JosephSemrai @Wathsara please help

**Comment by viraj-dhanushka** [comment]
I'm having this.. same Issue

![Screenshot (75)](https://user-images.githubusercontent.com/59219626/73585772-82659780-44ca-11ea-84f6-1567c97ac93d.png)

**Comment by Wathsara** [comment]
I think it might be because of the version issues of the node. Try it with node version 9 or 10 hope it will fix the issue?

**Comment by Wathsara** [comment]
It might be because of the version issues of node. Could u guys please try to build with the version node version 9, think it will fix the error.

**Comment by viraj-dhanushka** [comment]
@Wathsara Yeah the issue is with the node versions.. I opened a new issue #22  with some failed info..
