### ISSUE TITLE
Some previous node versions throw erros

### ISSUE THREAD

**Issue by viraj-dhanushka** [scorelab/AnimalRescue#23]
I tried to built the app with node version 9.11.2 and the app built was successful. But It gives this error while loading.

![Screenshot_1580546600](https://user-images.githubusercontent.com/59219626/73589582-fec59e00-44fd-11ea-8bd7-701a726830a2.png)

**Comment by viraj-dhanushka** [comment]
@Wathsara Can you tell me the node version of this project which you initially built with ❓

**Comment by Wathsara** [comment]
Press dismiss and try again it will work.
